account_id = ""
compatibility_date = "2022-05-14"
name = "remix-on-the-fridge"

main = "index.ts"

workers_dev = true

kv_namespaces = [
  { binding = "SESSION_KV", id = "3fa3ff56bb454b30878a5c7034869cf9", preview_id = "a1a2a6017f7f4c2485258ece761ca0c0" },
]

vars = {ENVIRONMENT = "production"}

[site]
bucket = "../../apps/remix-app/public"

[env.dev]
vars = [
  {SESSION_SECRET = "should-be-secure-in-prod"},
  {ENVIRONMENT = "development"}
]
kv_namespaces = [
  { binding = "SESSION_KV", id = "3fa3ff56bb454b30878a5c7034869cf9", preview_id = "a1a2a6017f7f4c2485258ece761ca0c0" },
]

[env.dev.durable_objects]
bindings = [
  {name = "COUNTER", class_name = "CounterDurableObject"},
  {name = "BOARD", class_name = "BoardDurableObject"},
  {name = "RATE_LIMITER", class_name = "RateLimiterDurableObject"},
  {name = "STICKY", class_name = "StickyDurableObject"},
  {name = "USER_STATE", class_name = "UserStateDurableObject"},
]

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "CounterDurableObject"},
  {name = "BOARD", class_name = "BoardDurableObject"},
  {name = "RATE_LIMITER", class_name = "RateLimiterDurableObject"},
  {name = "STICKY", class_name = "StickyDurableObject"},
  {name = "USER_STATE", class_name = "UserStateDurableObject"},
]

[[migrations]]
new_classes = ["CounterDurableObject", "BoardDurableObject", "RateLimiterDurableObject", "StickyDurableObject", "UserStateDurableObject"]
tag = "v1"

[[migrations]]
new_classes = ["StickyDurableObject", "UserStateDurableObject"]
tag = "v2"