account_id = ""
compatibility_date = "2022-05-14"
name = "remix-on-the-fridge"

main = "index.ts"

workers_dev = true

[site]
bucket = "../../apps/remix-app/public"

[env.dev]
vars = {SESSION_SECRET = "should-be-secure-in-prod"}

[env.dev.durable_objects]
bindings = [
  {name = "COUNTER", class_name = "CounterDurableObject"},
  {name = "BOARD", class_name = "BoardDurableObject"},
  {name = "RATE_LIMITER", class_name = "RateLimiterDurableObject"},
]

[durable_objects]
bindings = [
  {name = "COUNTER", class_name = "CounterDurableObject"},
  {name = "BOARD", class_name = "BoardDurableObject"},
  {name = "RATE_LIMITER", class_name = "RateLimiterDurableObject"},
]

[[migrations]]
new_classes = ["CounterDurableObject", "BoardDurableObject", "RateLimiterDurableObject"]
tag = "v1"